name = "Boxy"
license = "MIT"
licenselink = "https://akhlakm.github.io/"
description = "Boxy theme based on cupper hugo"
homepage = "https://akhlakm.github.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Akhlak Mahmood"
  homepage = "https://akhlakm.github.io/"

# If porting an existing theme
[original]
  name = "hugo-theme-cupper"
  homepage = "https://github.com/zwbetz-gh/cupper-hugo-theme"
  repo = "https://github.com/zwbetz-gh/cupper-hugo-theme"
